CAPTION = "first game"
FRAMERATE = 60
BOARDWIDTHNUM = 12
BOARDHEIGHTNUM = 23
NUMOFTETRIMINOSTATE = 4
NUMOFVISUALMINOQUEUE = 5
FAILTUPLE = (99,99)
HEIGHT = 20
WIDTH = 10
FIRSTLOCATION = (1,WIDTH/2)



SCREEN_WIDTH = 600
SCREEN_HEIGHT = 540
SCREEN_LEFT_SPACE = 175
SCREEN_RIGHT_SPACE = 175
SCREEN_TOP_SPACE = 20
SCREEN_BOTTOM_SPACE = 20
SCREEN_BOARD_WIDTH = SCREEN_WIDTH - SCREEN_LEFT_SPACE - SCREEN_RIGHT_SPACE
SCREEN_BOARD_HEIGHT = SCREEN_HEIGHT - SCREEN_TOP_SPACE - SCREEN_BOTTOM_SPACE
SCREEN_MINORECT_WIDTHANDHEIGHT = 75
SCREEN_MINORECT_TOP_BOTTOM_SPACE = (SCREEN_HEIGHT - SCREEN_MINORECT_WIDTHANDHEIGHT * NUMOFVISUALMINOQUEUE) / (NUMOFVISUALMINOQUEUE +1)
SCREEN_MINO_WIDTH = (SCREEN_WIDTH - SCREEN_LEFT_SPACE - SCREEN_RIGHT_SPACE) / WIDTH
SCREEN_MINO_HEIGHT = (SCREEN_HEIGHT - SCREEN_TOP_SPACE- SCREEN_BOTTOM_SPACE) / HEIGHT 

BOARD_COLOR = (100,100,100)
ZMINO_COLOR = (237,41,57)
LMINO_COLOR = (255,121,0)
OMINO_COLOR = (254,203,80)
SMINO_COLOR = (105,190,40)
IMINO_COLOR = (0,159,218)
JMINO_COLOR = (0,101,189)
TMINO_COLOR = (149,45,152)


