CAPTION = "first game"
FRAMERATE = 60
BOARDWIDTHNUM = 12
BOARDHEIGHTNUM = 23
NUMOFTETRIMINOSTATE = 4
NUMOFVISUALMINOQUEUE = 5
FAILTUPLE = (99,99)
HEIGHT = 23
WIDTH = 12
FIRSTLOCATION = (1,WIDTH/2 - 1)



SCREEN_WIDTH = 600
SCREEN_HEIGHT = 540
SCREEN_LEFT_SPACE = 175
SCREEN_RIGHT_SPACE = 175
SCREEN_TOP_SPACE = 20
SCREEN_BOTTOM_SPACE = 20
SCREEN_BOARD_WIDTH = SCREEN_WIDTH - SCREEN_LEFT_SPACE - SCREEN_RIGHT_SPACE
SCREEN_BOARD_HEIGHT = SCREEN_HEIGHT - SCREEN_TOP_SPACE - SCREEN_BOTTOM_SPACE
SCREEN_MINORECT_WIDTHANDHEIGHT = 75
SCREEN_MINORECT_TOP_BOTTOM_SPACE = (SCREEN_HEIGHT - SCREEN_MINORECT_WIDTHANDHEIGHT * NUMOFVISUALMINOQUEUE) / (NUMOFVISUALMINOQUEUE +1)


BOARD_COLOR = (100,100,100)



