CAPTION = "first game"
FRAMERATE = 60
NUMOFTETRIMINOSTATE = 4
NUMOFVISUALMINOQUEUE = 5
FAILTUPLE = (99,99)
BOARDHEIGHT = 20
BOARDWIDTH = 10
EXTRABOARDHEIGHT = 3
EXTRABOARDWIDTH = 2
FIRSTLOCATION = (1,BOARDWIDTH//2)



SCREEN_WIDTH = 600
SCREEN_HEIGHT = 540
SCREEN_LEFT_SPACE = 175
SCREEN_RIGHT_SPACE = 175
SCREEN_TOP_SPACE = 20
SCREEN_BOTTOM_SPACE = 20
SCREEN_BOARD_WIDTH = SCREEN_WIDTH - SCREEN_LEFT_SPACE - SCREEN_RIGHT_SPACE
SCREEN_BOARD_HEIGHT = SCREEN_HEIGHT - SCREEN_TOP_SPACE - SCREEN_BOTTOM_SPACE
SCREEN_MINORECT_WIDTHANDHEIGHT = 75
SCREEN_MINORECT_TOP_BOTTOM_SPACE = (SCREEN_HEIGHT - SCREEN_MINORECT_WIDTHANDHEIGHT * NUMOFVISUALMINOQUEUE) / (NUMOFVISUALMINOQUEUE +1)
SCREEN_MINO_WIDTH = (SCREEN_WIDTH - SCREEN_LEFT_SPACE - SCREEN_RIGHT_SPACE) / BOARDWIDTH
SCREEN_MINO_HEIGHT = (SCREEN_HEIGHT - SCREEN_TOP_SPACE- SCREEN_BOTTOM_SPACE) / BOARDHEIGHT 

BOARD_COLOR = (100,100,100)
ZMINO_COLOR = (237,41,57)
LMINO_COLOR = (255,121,0)
OMINO_COLOR = (254,203,80)
SMINO_COLOR = (105,190,40)
IMINO_COLOR = (0,159,218)
JMINO_COLOR = (0,101,189)
TMINO_COLOR = (149,45,152)

TETRIMINO_DROP_SPEED = 0

SOFT_MOVE_LIMIT_FRAME = 60 # 한 방향키를 꾹 눌렀을때 블럭이 빠르게 이동하기 시작하는데까지 필요한 임계 프레임수
SOFT_MOVE_DELAY_FRAME = 5# 소프트 이동시 MoveLeft,MoveRight함수가 호출될 프레임 간격
SOFT_DROP_DELAY_FRAME = 5# 소프트드랍시 MoveDown함수가 호출될 프레임 간격
AUTO_MOVE_DELAY_FRAME = 40# 자동으로 미노가 내려가는 프레임 간격
STACKING_DELAY_FRAME = 60# 미노가 바닥에 붙고 스태킹될때까지 걸리는 프레임간격


